documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "requirements-*.txt"
          - "renovate.json"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
