line-length = 80
target-version = "py312"
src = ["patches"]
extend-exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "SIM", "C4"]
ignore = ["E501", "E722"]
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
