name: Assign

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions: {}

jobs:
  assign:
    name: Assign
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Assign to the maintainer
        uses: pozil/auto-assign-issue@af6beea6bdf1e8eb373f061c5bc168681fc6d011 # v4.0.1
        with:
          assignees: ${{ github.repository_owner }}
          issueNumber: ${{ github.event.pull_request.number || github.event.issue.number }}
